
###主页地址：http://localhost:8095/index.html
server:
  port: 8095
security:
  basic:
    enabled: false
    # security
  user:
    name: admin
    password: 123

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/process-center?useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 123
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
